/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssetsMode: typeof import('./components/workbench/AssetsMode.vue')['default']
    ChapterPreviewTable: typeof import('./components/ChapterPreviewTable.vue')['default']
    CreateProjectModal: typeof import('./components/workbench/CreateProjectModal.vue')['default']
    EditProjectModal: typeof import('./components/EditProjectModal.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    ImportChaptersDrawer: typeof import('./components/workbench/ImportChaptersDrawer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NovelMode: typeof import('./components/workbench/NovelMode.vue')['default']
    NovelSourceInput: typeof import('./components/NovelSourceInput.vue')['default']
    NSpin: typeof import('naive-ui')['NSpin']
    PanelCard: typeof import('./components/PanelCard.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    ProjectDropdown: typeof import('./components/workbench/ProjectDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptMode: typeof import('./components/workbench/ScriptMode.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    StoryboardMode: typeof import('./components/workbench/StoryboardMode.vue')['default']
    TaskDrawer: typeof import('./components/workbench/TaskDrawer.vue')['default']
  }
}
